-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgdqSNoQB3yOqc8ynI
MSrTesIJAZif3Zi4FWlXATpkj26gCgYIKoZIzj0DAQehRANCAASuJor9zmWaWgPa
Xuh9lzf5OuAFyDyHTOsbOd1wX05oHjfEJR1gxXUTmWleNuUzvrdxrP9WEsvTTJxn
OIYoJzkX
-----END PRIVATE KEY-----