workflows:
  ios-build:
    name: iOS Release
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install Dart & Flutter dependencies
        script: |
          flutter pub get
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/ipa
