workflows:
  ios-build:
    name: iOS Release (IPA)
    environment:
      flutter: stable
      xcode: latest
      vars:
        BUNDLE_ID: com.KaranArjunTechnologies.fiinny 
    ios_signing:
      distribution_type: app_store
      bundle_identifier: com.KaranArjunTechnologies.fiinny 
    scripts:
      - name: Make sure Podfile targets iOS 15.5 (safety)
        script: |
          sed -i '' -e "s/platform :ios, '.*'/platform :ios, '15.5'/" ios/Podfile || true
          sed -i '' -e "s/\['IPHONEOS_DEPLOYMENT_TARGET'\] = '13.0'/['IPHONEOS_DEPLOYMENT_TARGET'] = '15.5'/" ios/Podfile || true
      - name: Flutter deps
        script: flutter pub get
      - name: Build IPA with automatic signing
        script: flutter build ipa --export-options-plist=ios/ExportOptions.plist
    artifacts:
      - build/ios/ipa/*.ipa
