workflows:
  ios-build:
    name: iOS Release
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build iOS (.ipa)
        script: |
          flutter build ios --release --no-codesign
          mkdir -p build/ios/ipa/Payload
          cp -r build/ios/iphoneos/Runner.app build/ios/ipa/Payload
          cd build/ios/ipa
          zip -r fiinny.ipa Payload
    artifacts:
      - build/ios/ipa/fiinny.ipa
