workflows:
  ios-build:
    name: iOS Release
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get

      - name: Build iOS app (no code sign)
        script: |
          flutter build ios --release --no-codesign

      - name: Create IPA manually
        script: |
          mkdir -p build/ios/ipa/Payload
          cp -r build/ios/iphoneos/Runner.app build/ios/ipa/Payload/
          cd build/ios/ipa
          zip -r Runner.ipa Payload

    artifacts:
      - build/ios/ipa/Runner.ipa
