workflows:
  ios-build:
    name: iOS Release
    environment:
      flutter: stable
      xcode: latest
    certificates:
      - bundle_identifier: com.fiinny.app
        certificate_url: Encrypted@SecureLinkToCert.p12
        certificate_password: Encrypted@CertPassword
        provisioning_profile_url: Encrypted@SecureLinkToMobileprovision
    publishing:
      app_store_connect:
        api_key: Encrypted@AppStoreConnectAPIKey
    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get

      - name: Build iOS app
        script: |
          flutter build ios --release

      - name: Archive the app
        script: |
          xcodebuild -workspace ios/Runner.xcworkspace \
                     -scheme Runner \
                     -sdk iphoneos \
                     -configuration Release \
                     -archivePath build/Runner.xcarchive \
                     archive

      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
                     -archivePath build/Runner.xcarchive \
                     -exportOptionsPlist ios/ExportOptions.plist \
                     -exportPath build/ios/ipa
    artifacts:
      - build/ios/ipa/*.ipa
