import type { Listing } from '@/types/listing';

// Ported 1:1 from seed() (index (1).html, main IIFE). Relative `created`
// offsets from Date.now() are preserved exactly, since freshness (NEW badge,
// "Added Today" hero stat) depends on them. Phase 7's Firestore cutover
// replaces this file — kept isolated here so it's a one-line swap later,
// per the architecture doc's "one function, one collection, one source of
// truth" principle.
//
// furnishing/availability/tenant_preference/amenities are NEW fields added
// in Phase 5 (see types/listing.ts) — the original data model never had
// them (architecture report §1.5). Values below are inferred from each
// listing's own description text, not invented arbitrarily.
export function getSeedListings(): Listing[] {
  const n = Date.now();
  return [
    {
      id: 's1',
      title: '2BHK in Koramangala',
      description:
        'Spacious 2BHK fully furnished flat available from May 1st. 24/7 water supply and power backup. Gated society with round-the-clock security. 5 mins walk to 5th block restaurants and cafes. Owner direct listing, absolutely no brokerage. Ideal for IT professionals or young couples.',
      rent: 28000,
      location: 'Koramangala 5th Block',
      city: 'Bangalore',
      type: '2BHK',
      tag: 'owner',
      owner_name: 'Ramesh Kumar',
      contact_phone: '9876543210',
      contact_email: 'ramesh@example.com',
      image_urls: [
        'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=700&q=80',
        'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=700&q=80',
      ],
      fb_url: '',
      lat: 12.9352,
      lng: 77.6245,
      created: new Date(n - 18 * 60000).toISOString(),
      available: true,
      views: 24,
      source: 'seed',
      status: 'published',
      hidden: false,
      furnishing: 'Fully Furnished',
      availability: 'Within 30 Days',
      tenant_preference: 'Anyone',
      amenities: ['Security', 'Power Backup'],
    },
    {
      id: 's2',
      title: 'Flatmate Needed – HSR Layout',
      description:
        'Looking for a working female flatmate in a bright 3BHK apartment. Your room is fully furnished with AC and wardrobe. No food restrictions whatsoever. Society amenities include gym, swimming pool and 24/7 security. Very friendly flatmates already living here. WhatsApp preferred for first contact.',
      rent: 14000,
      location: 'HSR Layout Sector 2',
      city: 'Bangalore',
      type: 'Flatmate',
      tag: 'flatmate',
      owner_name: 'Priya Sharma',
      contact_phone: '9123456789',
      contact_email: 'priya@example.com',
      image_urls: [
        'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=700&q=80',
        'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=700&q=80',
      ],
      fb_url: '',
      lat: 12.9116,
      lng: 77.6389,
      created: new Date(n - 45 * 60000).toISOString(),
      available: true,
      views: 11,
      source: 'seed',
      status: 'published',
      hidden: false,
      furnishing: 'Fully Furnished',
      availability: 'Immediate',
      tenant_preference: 'Female',
      amenities: ['Gym', 'Pool', 'Security'],
    },
    {
      id: 's3',
      title: '1BHK Semi-Furnished – Indiranagar',
      description:
        '1BHK on the 2nd floor with an attached balcony offering nice cross-ventilation. Modular kitchen with chimney included. Building has lift and security guard. 5-minute walk to Indiranagar metro station. Broker listing — 1 month brokerage applicable. Call or WhatsApp for site visit.',
      rent: 20000,
      location: 'Indiranagar 12th Main',
      city: 'Bangalore',
      type: '1BHK',
      tag: 'broker',
      owner_name: 'Suresh Realty',
      contact_phone: null,
      contact_email: '',
      image_urls: ['https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=700&q=80'],
      fb_url: 'https://facebook.com/groups/blr_flats/posts/sample123',
      lat: 12.9784,
      lng: 77.6408,
      created: new Date(n - 2 * 3600000).toISOString(),
      available: true,
      views: 38,
      source: 'seed',
      status: 'published',
      hidden: false,
      furnishing: 'Semi Furnished',
      availability: 'Immediate',
      tenant_preference: 'Anyone',
      amenities: ['Lift', 'Security'],
    },
    {
      id: 's4',
      title: '2BHK in Madhapur HITEC City',
      description:
        'Brand new 2BHK in the heart of Madhapur IT corridor. Both rooms available for separate occupancy. Fully furnished with premium furniture. 24/7 power backup and security. Dedicated parking slot. Owner self, zero brokerage. Ideal for IT couple or two working professionals who want to share.',
      rent: 25000,
      location: 'Madhapur HITEC City',
      city: 'Hyderabad',
      type: '2BHK',
      tag: 'owner',
      owner_name: 'Anil Reddy',
      contact_phone: '8765432100',
      contact_email: 'anil@example.com',
      image_urls: [
        'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=700&q=80',
        'https://images.unsplash.com/photo-1586105251261-72a756497a11?w=700&q=80',
      ],
      fb_url: '',
      lat: 17.4486,
      lng: 78.3908,
      created: new Date(n - 3600000).toISOString(),
      available: true,
      views: 17,
      source: 'seed',
      status: 'published',
      hidden: false,
      furnishing: 'Fully Furnished',
      availability: 'Immediate',
      tenant_preference: 'Anyone',
      amenities: ['Parking', 'Power Backup', 'Security'],
    },
    {
      id: 's5',
      title: 'Flatmate Wanted – DLF Cyber City',
      description:
        'One well-furnished room available in a premium 3BHK apartment very close to DLF Cyber City and Golf Course Road. Male working professional preferred. Rent includes monthly maintenance charges. Netflix and Amazon Prime accounts shared among flatmates. Immediate occupancy available.',
      rent: 16500,
      location: 'DLF Phase 2',
      city: 'Gurgaon',
      type: 'Flatmate',
      tag: 'flatmate',
      owner_name: 'Vikram Singh',
      contact_phone: '7012345678',
      contact_email: 'vikram@example.com',
      image_urls: ['https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=700&q=80'],
      fb_url: '',
      lat: 28.4958,
      lng: 77.0886,
      created: new Date(n - 30 * 60000).toISOString(),
      available: true,
      views: 6,
      source: 'seed',
      status: 'published',
      hidden: false,
      furnishing: 'Fully Furnished',
      availability: 'Immediate',
      tenant_preference: 'Male',
      amenities: [],
    },
    {
      id: 's6',
      title: '1BHK Independent House – Whitefield',
      description:
        'Charming independent 1BHK house with an exclusive private garden — perfect for morning yoga or evening unwinding. Pet-friendly property with kind neighbours. Very quiet and green locality, just 3 minutes from ITPL main gate. Owner direct listing, no broker involved at any stage.',
      rent: 18000,
      location: 'Whitefield',
      city: 'Bangalore',
      type: '1BHK',
      tag: 'owner',
      owner_name: 'Deepa Nair',
      contact_phone: '9988776655',
      contact_email: 'deepa@example.com',
      image_urls: [
        'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=700&q=80',
        'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=700&q=80',
      ],
      fb_url: '',
      lat: 12.9698,
      lng: 77.7499,
      created: new Date(n - 5 * 3600000).toISOString(),
      available: true,
      views: 52,
      source: 'seed',
      status: 'published',
      hidden: false,
      furnishing: 'Unfurnished',
      availability: 'Immediate',
      tenant_preference: 'Anyone',
      amenities: [],
    },
    {
      id: 's7',
      title: '3BHK Premium Flat – Jubilee Hills',
      description:
        'Luxurious 3BHK apartment in the most sought-after address of Jubilee Hills. Fully furnished with designer furniture and premium fittings throughout. Society has a large clubhouse, Olympic-size swimming pool, tennis court and fully equipped gym. Owner self listing — no broker commission required.',
      rent: 45000,
      location: 'Jubilee Hills Road 36',
      city: 'Hyderabad',
      type: '2BHK',
      tag: 'owner',
      owner_name: 'Mahesh Rao',
      contact_phone: '9345678901',
      contact_email: '',
      image_urls: ['https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?w=700&q=80'],
      fb_url: '',
      lat: 17.4312,
      lng: 78.4079,
      created: new Date(n - 8 * 3600000).toISOString(),
      available: true,
      views: 29,
      source: 'seed',
      status: 'published',
      hidden: false,
      furnishing: 'Fully Furnished',
      availability: 'Immediate',
      tenant_preference: 'Anyone',
      amenities: ['Pool', 'Gym', 'Security'],
    },
    {
      id: 's8',
      title: 'Studio 1BHK – Sector 56 Gurgaon',
      description:
        'Compact but smartly designed studio apartment with fully modular kitchen, built-in wardrobe and good natural light. Ideal for a single working professional who values location over space. 10 minutes drive to Cyber City. Broker listing — one month brokerage charged at time of agreement.',
      rent: 12000,
      location: 'Sector 56',
      city: 'Gurgaon',
      type: '1BHK',
      tag: 'broker',
      owner_name: 'Gaurav Properties',
      contact_phone: null,
      contact_email: '',
      image_urls: ['https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=700&q=80'],
      fb_url: 'https://facebook.com/groups/gurgaon_flats/posts/sample456',
      lat: 28.4207,
      lng: 77.084,
      created: new Date(n - 6 * 3600000).toISOString(),
      available: true,
      views: 19,
      source: 'seed',
      status: 'published',
      hidden: false,
      furnishing: 'Semi Furnished',
      availability: 'Immediate',
      tenant_preference: 'Anyone',
      amenities: [],
    },
    {
      id: 's9',
      title: '2BHK near Inorbit Mall',
      description:
        'Neat 2BHK apartment just 500 metres from Inorbit Mall Whitefield. Semi-furnished — beds, wardrobes and kitchen appliances included. Society has children play area and jogging track. Owner self, no brokerage at all. Available from 1st of next month. Ideal for families or working couple.',
      rent: 22000,
      location: 'Whitefield near Inorbit',
      city: 'Bangalore',
      type: '2BHK',
      tag: 'owner',
      owner_name: 'Girish Bhat',
      contact_phone: '8123456700',
      contact_email: 'girish@example.com',
      image_urls: ['https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=700&q=80'],
      fb_url: '',
      lat: 12.9819,
      lng: 77.7308,
      created: new Date(n - 10 * 3600000).toISOString(),
      available: true,
      views: 33,
      source: 'seed',
      status: 'published',
      hidden: false,
      furnishing: 'Semi Furnished',
      availability: 'Within 30 Days',
      tenant_preference: 'Family',
      amenities: [],
    },
    {
      id: 's10',
      title: 'Female Flatmate – Kondapur',
      description:
        'One spacious room available in a 3BHK flat in Kondapur, Hyderabad. Strictly looking for a working female. Flat is fully air-conditioned. Separate attached bathroom for your room. 2-minute walk to bus stop. Electricity bill shared equally. Looking for flatmate from next month.',
      rent: 11000,
      location: 'Kondapur',
      city: 'Hyderabad',
      type: 'Flatmate',
      tag: 'flatmate',
      owner_name: 'Sneha Iyer',
      contact_phone: '9234567801',
      contact_email: '',
      image_urls: [
        'https://images.unsplash.com/photo-1586105251261-72a756497a11?w=700&q=80',
        'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=700&q=80',
      ],
      fb_url: '',
      lat: 17.4615,
      lng: 78.3568,
      created: new Date(n - 25 * 60000).toISOString(),
      available: true,
      views: 8,
      source: 'seed',
      status: 'published',
      hidden: false,
      furnishing: 'Fully Furnished',
      availability: 'Within 30 Days',
      tenant_preference: 'Female',
      amenities: [],
    },
    {
      id: 's11',
      title: '1BHK near Cyber Hub Gurgaon',
      description:
        'Cozy 1BHK apartment in a well-maintained building just 1.2 km from Cyber Hub. Fully furnished with all appliances. Biometric entry, CCTV in common areas. Excellent for MNC professionals working in DLF or Cyber City area. Owner listing, no broker fees. Call directly.',
      rent: 17500,
      location: 'Sector 24',
      city: 'Gurgaon',
      type: '1BHK',
      tag: 'owner',
      owner_name: 'Anoop Sharma',
      contact_phone: '7890123456',
      contact_email: 'anoop@example.com',
      image_urls: ['https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=700&q=80'],
      fb_url: '',
      lat: 28.5013,
      lng: 77.0897,
      created: new Date(n - 4 * 3600000).toISOString(),
      available: true,
      views: 14,
      source: 'seed',
      status: 'published',
      hidden: false,
      furnishing: 'Fully Furnished',
      availability: 'Immediate',
      tenant_preference: 'Anyone',
      amenities: ['Security'],
    },
    {
      id: 's12',
      title: '3BHK Sharing – Marathahalli',
      description:
        'One room available in a large 3BHK flat in Marathahalli. Two professionals already staying. Flat is semi-furnished and very clean. Separate room lock. Society has gym. Ideal for a working professional who is looking for flatmate arrangement at affordable price point.',
      rent: 9500,
      location: 'Marathahalli',
      city: 'Bangalore',
      type: 'Flatmate',
      tag: 'flatmate',
      owner_name: 'Karthik M',
      contact_phone: '9567890123',
      contact_email: '',
      image_urls: ['https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=700&q=80'],
      fb_url: '',
      lat: 12.9592,
      lng: 77.6967,
      created: new Date(n - 1.5 * 3600000).toISOString(),
      available: true,
      views: 21,
      source: 'seed',
      status: 'published',
      hidden: false,
      furnishing: 'Semi Furnished',
      availability: 'Immediate',
      tenant_preference: 'Anyone',
      amenities: ['Gym'],
    },
  ];
}
