// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABuimmTbHwrxY-w7xhRrf-LWOu4gLVfnk',
    appId: '1:1085936196639:android:b74ffa7e9ded49e616492a',
    messagingSenderId: '1085936196639',
    projectId: 'lifemap-72b21',
    storageBucket: 'lifemap-72b21.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt-xTvI1TGF3AlFSeR5rVpzfC14D4v_iY',
    appId: '1:1085936196639:ios:3cbdc12cca308cbc16492a',
    messagingSenderId: '1085936196639',
    projectId: 'lifemap-72b21',
    storageBucket: 'lifemap-72b21.firebasestorage.app',
    androidClientId: '1085936196639-11mjkb68f4k99m8ebs7g0rn5hr0ee2cn.apps.googleusercontent.com',
    iosClientId: '1085936196639-ful1a37opigvpkrfnkvkpitue5fcbd00.apps.googleusercontent.com',
    iosBundleId: 'com.KaranArjunTechnologies.fiinny',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7HqSl9YZE9MkQ-_pjbNtS9Lcv679zy2Q',
    appId: '1:1085936196639:web:b0f063c3c95b347f16492a',
    messagingSenderId: '1085936196639',
    projectId: 'lifemap-72b21',
    authDomain: 'lifemap-72b21.firebaseapp.com',
    storageBucket: 'lifemap-72b21.firebasestorage.app',
    measurementId: 'G-GCS6LCXNHW',
  );
}
