import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // <-- generated by flutterfire configure

import 'package:timezone/data/latest.dart' as tz;

import 'package:lifemap/themes/theme_provider.dart';
import './services/notification_service.dart';

import 'screens/launcher_screen.dart';
// import 'screens/auth_gate.dart'; // keep if you plan to switch home to AuthGate later
import 'routes.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // Timezone DB (for flutter_local_notifications scheduling)
  tz.initializeTimeZones();

  // Firebase with per-platform options (works for both Android & iOS)
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Local notifications (your service handles platform specifics)
  await NotificationService.initialize();

  // Theme provider init
  final themeProvider = ThemeProvider();
  await themeProvider.loadTheme();

  runApp(
    ChangeNotifierProvider.value(
      value: themeProvider,
      child: const FiinnyApp(),
    ),
  );
}

class FiinnyApp extends StatelessWidget {
  const FiinnyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final themeProvider = Provider.of<ThemeProvider>(context);

    return MaterialApp(
      title: 'Fiinny',
      debugShowCheckedModeBanner: false,
      theme: themeProvider.themeData,
      home: const LauncherScreen(),
      routes: appRoutes,
      onGenerateRoute: appOnGenerateRoute,
    );
  }
}
