# ios/Podfile

platform :ios, '15.5'

# Load the Flutter engine and plugins
require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), __dir__)

use_frameworks!
use_modular_headers!

target 'Runner' do
  flutter_install_all_ios_pods(File.dirname(File.realpath(__FILE__)))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
  end
end
