name: iOS IPA (archive, export, upload)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "ios/**"
      - "lib/**"
      - "pubspec.*"
      - ".github/workflows/**"

concurrency:
  group: ios-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ios:
    runs-on: macos-14
    env:
      BUNDLE_ID: ${{ secrets.BUNDLE_ID }}
      TEAM_ID: ${{ secrets.TEAM_ID }}
      P12_BASE64: ${{ secrets.P12_BASE64 }}
      P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
      PROVISIONING_PROFILE_BASE64: ${{ secrets.PROVISIONING_PROFILE_BASE64 }}
      APPLE_KEY_ID: ${{ secrets.APPLE_KEY_ID }}
      APPLE_ISSUER_ID: ${{ secrets.APPLE_ISSUER_ID }}
      APPLE_API_KEY_BASE64: ${{ secrets.APPLE_API_KEY_BASE64 }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode (latest 16.x)
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16'

      # ---- CACHES -----------------------------------------------------------
      - name: Cache CocoaPods
        uses: actions/cache@v4
        with:
          path: |
            ~/.cocoapods/repos
            ~/Library/Caches/CocoaPods
            ios/Pods
          key: pods-${{ runner.os }}-xcode16-${{ hashFiles('ios/Podfile.lock') }}
          restore-keys: |
            pods-${{ runner.os }}-xcode16-

      - name: Cache Flutter pub cache
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: pub-${{ runner.os }}-${{ hashFiles('pubspec.lock') }}
          restore-keys: |
            pub-${{ runner.os }}-

      - name: Cache Xcode DerivedData
        uses: actions/cache@v4
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: dd-${{ runner.os }}-xcode16-${{ hashFiles('ios/Podfile.lock', 'ios/Runner.xcodeproj/project.pbxproj') }}
          restore-keys: |
            dd-${{ runner.os }}-xcode16-

      # ---- TOOLING ----------------------------------------------------------
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Install CocoaPods & xcbeautify
        shell: bash
        run: |
          set -euxo pipefail
          sudo gem install cocoapods -N || true
          brew install xcbeautify || true

      # ---- DEPENDENCIES -----------------------------------------------------
      - name: Flutter pub get
        run: flutter pub get

      - name: Enforce iOS 16 floor & clean Pods (prevents linker mismatch)
        shell: bash
        run: |
          set -euxo pipefail
          /usr/bin/sed -i '' "s/platform :ios, .*/platform :ios, '16.0'/" ios/Podfile || true
          rm -rf ios/Pods ios/Podfile.lock

      - name: Install Pods
        shell: bash
        run: |
          set -euxo pipefail
          cd ios
          pod repo update
          pod install --repo-update --clean-install
          cd ..

      # ---- CODE SIGNING (manual, using your P12 + profile) ------------------
      - name: Create keychain & import .p12
        shell: bash
        run: |
          set -euxo pipefail
          KEYCHAIN="$RUNNER_TEMP/build.keychain"
          KPWD=$(uuidgen)
          security create-keychain -p "$KPWD" "$KEYCHAIN"
          security set-keychain-settings -lut 21600 "$KEYCHAIN"
          security unlock-keychain -p "$KPWD" "$KEYCHAIN"
          printf '%s' "$P12_BASE64" | base64 -D > cert.p12
          security import cert.p12 -k "$KEYCHAIN" -P "$P12_PASSWORD" -A
          security list-keychains -s "$KEYCHAIN" $(security list-keychains | sed 's/["]//g')
          security default-keychain -s "$KEYCHAIN"

      - name: Install provisioning profile
        shell: bash
        run: |
          set -euxo pipefail
          mkdir -p "$HOME/Library/MobileDevice/Provisioning Profiles"
          printf '%s' "$PROVISIONING_PROFILE_BASE64" | base64 -D > "$RUNNER_TEMP/profile.mobileprovision"
          DECODED_PLIST="$RUNNER_TEMP/profile.plist"
          /usr/bin/security cms -D -i "$RUNNER_TEMP/profile.mobileprovision" -o "$DECODED_PLIST"
          PROFILE_UUID=$(/usr/libexec/PlistBuddy -c "Print :UUID" "$DECODED_PLIST")
          PROFILE_NAME=$(/usr/libexec/PlistBuddy -c "Print :Name" "$DECODED_PLIST")
          APP_ID=$(/usr/libexec/PlistBuddy -c 'Print :Entitlements:application-identifier' "$DECODED_PLIST")
          PF_BUNDLE_ID="${APP_ID#*.}"
          echo "PROFILE_NAME=$PROFILE_NAME" >> "$GITHUB_ENV"
          echo "PROFILE_UUID=$PROFILE_UUID" >> "$GITHUB_ENV"
          echo "Resolved BundleId from profile: $PF_BUNDLE_ID"
          test "$PF_BUNDLE_ID" = "$BUNDLE_ID"
          cp "$RUNNER_TEMP/profile.mobileprovision" "$HOME/Library/MobileDevice/Provisioning Profiles/$PROFILE_UUID.mobileprovision"

      # ---- BUILD (quiet, pretty logs) ---------------------------------------
      - name: Show resolved build settings (sanity)
        shell: bash
        run: |
          set -euxo pipefail
          xcodebuild \
            -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -showBuildSettings \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID" \
            PROVISIONING_PROFILE_SPECIFIER="$PROFILE_NAME" \
            CODE_SIGN_IDENTITY="Apple Distribution" \
          | egrep 'PRODUCT_BUNDLE_IDENTIFIER|DEVELOPMENT_TEAM|CODE_SIGN_STYLE|PROVISIONING_PROFILE_SPECIFIER|CODE_SIGN_IDENTITY'

      - name: Archive (Xcode)
        shell: bash
        run: |
          set -euxo pipefail
          xcodebuild \
            -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -configuration Release \
            -sdk iphoneos \
            -archivePath build/Runner.xcarchive \
            clean archive \
            CODE_SIGN_STYLE=Manual \
            DEVELOPMENT_TEAM="$TEAM_ID" \
            PRODUCT_BUNDLE_IDENTIFIER="$BUNDLE_ID" \
            PROVISIONING_PROFILE_SPECIFIER="$PROFILE_NAME" \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            | xcbeautify --quiet

      - name: Create ExportOptions.plist (app-store, manual)
        shell: bash
        run: |
          set -euxo pipefail
          EXPORT_OPTS="ios/ExportOptions.plist"
          /usr/libexec/PlistBuddy -c 'Clear dict' "$EXPORT_OPTS" 2>/dev/null || true
          /usr/libexec/PlistBuddy -c 'Add : dict' "$EXPORT_OPTS"
          /usr/libexec/PlistBuddy -c 'Add :method string app-store' "$EXPORT_OPTS"
          /usr/libexec/PlistBuddy -c 'Add :signingStyle string manual' "$EXPORT_OPTS"
          /usr/libexec/PlistBuddy -c "Add :teamID string ${TEAM_ID}" "$EXPORT_OPTS"
          /usr/libexec/PlistBuddy -c 'Add :provisioningProfiles dict' "$EXPORT_OPTS"
          /usr/libexec/PlistBuddy -c "Add :provisioningProfiles:${BUNDLE_ID} string ${PROFILE_NAME}" "$EXPORT_OPTS"
          /usr/libexec/PlistBuddy -c 'Add :stripSwiftSymbols bool true' "$EXPORT_OPTS"
          /usr/libexec/PlistBuddy -c 'Add :compileBitcode bool false' "$EXPORT_OPTS"
          /usr/libexec/PlistBuddy -c 'Add :destination string export' "$EXPORT_OPTS"

      - name: Export IPA
        shell: bash
        run: |
          set -euxo pipefail
          xcodebuild -exportArchive \
            -archivePath build/Runner.xcarchive \
            -exportOptionsPlist ios/ExportOptions.plist \
            -exportPath build \
            | xcbeautify --quiet
          ls -lah build || true
          if [ -f build/Runner.ipa ]; then mv build/Runner.ipa build/Fiinny.ipa; fi

      # ---- ARTIFACTS & UPLOAD ----------------------------------------------
      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: fiinny-ipa
          path: build/Fiinny.ipa

      - name: Write App Store Connect API key
        shell: bash
        run: |
          set -euxo pipefail
          echo "$APPLE_API_KEY_BASE64" | base64 --decode > "AuthKey_${APPLE_KEY_ID}.p8"

      - name: Upload to TestFlight (Transporter API key)
        shell: bash
        env:
          ASC_KEY_ID: ${{ env.APPLE_KEY_ID }}
          ASC_ISSUER_ID: ${{ env.APPLE_ISSUER_ID }}
        run: |
          set -euxo pipefail
          mkdir -p "$HOME/.appstoreconnect/private_keys"
          cp "AuthKey_${ASC_KEY_ID}.p8" "$HOME/.appstoreconnect/private_keys/AuthKey_${ASC_KEY_ID}.p8"
          xcrun iTMSTransporter -m upload \
            -assetFile build/Fiinny.ipa \
            -apiKey "$ASC_KEY_ID" \
            -apiIssuer "$ASC_ISSUER_ID" \
            -v informational
